spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres_course:5432/mydatabase}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${REDIS_HOST:redis_course}
    post: ${REDIS_PORT:6379}
  elasticsearch:
    uris: ${ES_URIS:https://my-elasticsearch-project-f3c1ba.es.us-central1.gcp.elastic.cloud:443}
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:M2JXOFpac0IyTUZfemVjTnMtRGU6RUh4UHNDQkw1SGthQXJ1UTNreTQtUQ==}
    connection-timeout: 5s
    socket-timeout: 3s

frontend:
  uri: ${FRONTEND_URI:http://localhost:5173}

livekit:
  api:
    key: ${LIVEKIT_API_KEY:devkey}
    secret: ${LIVEKIT_API_SECRET:9b25f27e04740eb052537dd8896c768edff8ee6a7dfa73df6aeb1b90371526f837db4d6b6bcdedcc87624012a476918e2f3718b13b3e51bead4ac033c195d84e}
  url: ${LIVEKIT_URL:http://livekit:7880}
